name: Ollama_GPU_CPU

services:
  ollama_gpu:
    image: ollama/ollama:rocm
    container_name: Ollama_GPU
    ports:
      - "22545:11434"
    volumes:
      - ollama-gpu:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    restart: unless-stopped

  ollama_cpu:
    image: ollama/ollama:latest
    container_name: Ollama_CPU
    ports:
      - "22546:11434"
    volumes:
      - ollama-cpu:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

volumes:
  ollama-gpu:
  ollama-cpu:

